feat(command): Populating Command Search and Adding State
RocketCommunicationsInc/ttc-command-react pull request #10
Opened 2023-07-21 18:05 UTC by FMorrison87

- Adding Commands.json to the utils folder.
- Populating the search commands input with the data from the Commands json file.
- Extracting the command search out to a new component within PassPlan.
- Setting up state in the PassPlan component and passing it down to the SearchCommands component.
- Adding click handler to the Add To Queue button to pass selected command back up to PassPlan.

2023-07-21 18:58 UTC, NicDominguez requested changes
Great work! Just have a couple requests/suggestions

2023-07-21 18:58 UTC, NicDominguez commented on src/Command/Components/PassPlan/SearchCommands/SearchCommands.tsx
> +        <RuxMenu className="commands_input-menu" onRuxmenuselected={(e) => selectCommand(e)}>
Its just an opinion of mine but if the handler only does a one line setState function I would prefer it just passed in directly to the prop so `onRuxmenuselected={(e) => setCommand(e.detail.value)}`

2023-07-21 18:58 UTC, NicDominguez commented on src/Command/Components/PassPlan/PassPlan.tsx
> +    if (commandListItem === '') return;
How about we disable the Add to Queue button until it has a valid command rather than have it do nothing?

2023-07-21 18:58 UTC, NicDominguez commented on src/Command/Components/PassPlan/SearchCommands/SearchCommands.css
Can we limit the height of the commands pop up a bit more? It feels like it takes too much screen real estate when open.

2023-07-24 13:58 UTC, FMorrison87 commented on src/Command/Components/PassPlan/PassPlan.tsx
> +    if (commandListItem === '') return;
This is actually something I've got hooked up in a different PR.

2023-07-24 14:00 UTC, FMorrison87 commented on src/Command/Components/PassPlan/SearchCommands/SearchCommands.css
Can do!

2023-07-24 16:08 UTC, NicDominguez approved these changes

2023-07-24 16:08 UTC, merged